#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        XPATH="/config/system/notification/notifications"

        if ! omv_config_exists "${XPATH}/notification[id='luks']"; then
            object="<uuid>$(omv_uuid)</uuid>"
            object="${object}<id>luks</id>"
            object="${object}<enable>0</enable>"
            omv_config_add_node_data "${XPATH}" "notification" "${object}"
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
