#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

KEYDIR="/etc/openmediavault/luks"
SETTINGS_XPATH_NAME="luks"
SETTINGS_XPATH="/config/system/storage/${SETTINGS_XPATH_NAME}"

case "$1" in
    purge)
        if omv_config_exists "${SETTINGS_XPATH}"; then
            omv_config_delete "${SETTINGS_XPATH}"
        fi
    ;;

    remove)
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
